language: node_js
node_js:
- '6'
cache:
  yarn: true
  directories:
  - node_modules
deploy:
  provider: npm
  email: iturgeon+npm@gmail.com
  on:
    tags: true
    repo: ucfopen/Materia-Widget-Dev-Kit
  api_key:
    secure: ZSoXqFZRB6pgO2j6E8XbvIkqjqENrLHCI9AfqNTPG85EtsU4rpXMiI9WtZWL7n5R4R58yzLvc9+6exqSzSESYdNF+VfIanY2utsaHrYiZcUwSI5vgvLHEg1Pvmh40A0ERbblP/LNKfy2ofyczBvBB1zz4CLZBTUTWOSI8fm0CNQ2iSr9wxetG0jO3+v+gcC3MDE5t+DvuaQedXI8VKnRvhLPypuxX/ONEiOe3HK3lDOlJCbL6acHGXstn/wKJ3vHOBKMEbAB4SWtik0En9fKYmV8xXp3OIAFjWxNZmWbDYRIKVn2Eyrm2G7CKc/R9uTEyowOK9d7832hafkoPW/Fa6JZJufcR4AbfUUWPuCZT7mtjBoP42QSUlhkkLP4kkcYXxJeOEAFq5taw0TScxKHfUIKK/GBjDoXDFbOnxDNRLk2Zu402APwHaR2KpysRXowDrgl+O5HJnmj7XApRrR6TfMA8oKym2D0YoDRPE/8diu8YMrtmpjMcPXvXacax1GpVp59W0CunN9+zrxvO7Oy4gAhvZZF2FJfSPBkd7LA8u8Hxmrn1vgE/MFHfeA8morkXzwlDBQ2Edsh4/k0VsE4FeQkljN1/D0ckSQRIOwlzb0dZnaSh5s61eV3lWApbv8OZ6IWyC+Uz3hROnEHAs6hvbGe7xwcB/aMvXjO7017gew=
